from __future__ import annotations

import ast
import fnmatch
import subprocess
from pathlib import Path, PurePosixPath
from typing import Mapping

from scripts.architecture_gate.models import ArchitectureSnapshot, FileMetric, Policy


def effective_loc(source: str) -> int:
    """Count non-blank, non-comment-only physical lines."""

    return sum(
        1
        for line in source.splitlines()
        if (stripped := line.strip()) and not stripped.startswith("#")
    )


def current_sources(root: Path, policy: Policy) -> dict[str, str]:
    sources: dict[str, str] = {}
    for source_root in policy.source_roots:
        absolute_root = root / source_root
        if not absolute_root.is_dir():
            continue
        for path in sorted(absolute_root.rglob("*.py")):
            relative = path.relative_to(root).as_posix()
            source = path.read_text(encoding="utf-8")
            if not _is_excluded(relative, source, policy):
                sources[relative] = source
    return sources


def git_sources(root: Path, policy: Policy, base_ref: str) -> dict[str, str]:
    listed = subprocess.run(
        ["git", "ls-tree", "-r", "--name-only", base_ref, "--", *policy.source_roots],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    )
    sources: dict[str, str] = {}
    for relative in sorted(line for line in listed.stdout.splitlines() if line.endswith(".py")):
        shown = subprocess.run(
            ["git", "show", f"{base_ref}:{relative}"],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        )
        if not _is_excluded(relative, shown.stdout, policy):
            sources[relative] = shown.stdout
    return sources


def build_snapshot(sources: Mapping[str, str], policy: Policy) -> ArchitectureSnapshot:
    module_by_path = {
        path: module
        for path in sorted(sources)
        if (module := _module_name(path, policy.source_roots)) is not None
    }
    path_by_module = {module: path for path, module in module_by_path.items()}
    known_modules = frozenset(path_by_module)
    graph: dict[str, set[str]] = {module: set() for module in known_modules}

    for path, module in module_by_path.items():
        graph[module].update(
            _module_imports(
                module,
                path.endswith("/__init__.py"),
                sources[path],
                known_modules,
            )
        )
        graph[module].discard(module)

    cycles = _strongly_connected_cycles(graph)
    files = {
        path: FileMetric(
            effective_loc=effective_loc(sources[path]),
            fan_out=len(graph[module]),
            module=module,
        )
        for path, module in sorted(module_by_path.items())
    }
    size_exempt_paths = frozenset(
        path
        for path in files
        if any(fnmatch.fnmatch(path, rule.pattern) for rule in policy.exceptions)
    )
    return ArchitectureSnapshot(
        files=files,
        cycles=cycles,
        size_exempt_paths=size_exempt_paths,
    )


def module_path(snapshot: ArchitectureSnapshot, module: str) -> str | None:
    return next(
        (path for path, metric in snapshot.files.items() if metric.module == module),
        None,
    )


def _is_excluded(relative: str, source: str, policy: Policy) -> bool:
    if any(fnmatch.fnmatch(relative, pattern) for pattern in policy.exclude):
        return True
    header = "\n".join(source.splitlines()[:5]).lower()
    return any(marker in header for marker in ("generated by", "@generated", "do not edit"))


def _module_name(path: str, source_roots: tuple[str, ...]) -> str | None:
    pure_path = PurePosixPath(path)
    for source_root in source_roots:
        root_path = PurePosixPath(source_root)
        try:
            relative = pure_path.relative_to(root_path)
        except ValueError:
            continue
        parts = list(relative.with_suffix("").parts)
        if parts and parts[-1] == "__init__":
            parts.pop()
        return ".".join(parts) or None
    return None


def _module_imports(
    module: str,
    is_package: bool,
    source: str,
    known_modules: frozenset[str],
) -> set[str]:
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return set()

    dependencies: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                if target := _known_target(alias.name, known_modules):
                    dependencies.add(target)
        elif isinstance(node, ast.ImportFrom):
            base = _import_from_base(module, is_package, node)
            for alias in node.names:
                candidate = f"{base}.{alias.name}" if base and alias.name != "*" else base
                target = _known_target(candidate, known_modules) or _known_target(
                    base, known_modules
                )
                if target:
                    dependencies.add(target)
    return dependencies


def _import_from_base(module: str, is_package: bool, node: ast.ImportFrom) -> str:
    if node.level == 0:
        return node.module or ""
    package_parts = module.split(".") if is_package else module.split(".")[:-1]
    ascend = node.level - 1
    if ascend > len(package_parts):
        return ""
    base_parts = package_parts[: len(package_parts) - ascend]
    if node.module:
        base_parts.extend(node.module.split("."))
    return ".".join(base_parts)


def _known_target(name: str, known_modules: frozenset[str]) -> str | None:
    candidate = name
    while candidate:
        if candidate in known_modules:
            return candidate
        candidate = candidate.rpartition(".")[0]
    return None


def _strongly_connected_cycles(
    graph: Mapping[str, set[str]],
) -> tuple[tuple[str, ...], ...]:
    index = 0
    indices: dict[str, int] = {}
    lowlinks: dict[str, int] = {}
    stack: list[str] = []
    on_stack: set[str] = set()
    components: list[tuple[str, ...]] = []

    def visit(node: str) -> None:
        nonlocal index
        indices[node] = index
        lowlinks[node] = index
        index += 1
        stack.append(node)
        on_stack.add(node)

        for dependency in sorted(graph[node]):
            if dependency not in indices:
                visit(dependency)
                lowlinks[node] = min(lowlinks[node], lowlinks[dependency])
            elif dependency in on_stack:
                lowlinks[node] = min(lowlinks[node], indices[dependency])

        if lowlinks[node] != indices[node]:
            return
        component: list[str] = []
        while True:
            member = stack.pop()
            on_stack.remove(member)
            component.append(member)
            if member == node:
                break
        if len(component) > 1:
            components.append(tuple(sorted(component)))

    for node in sorted(graph):
        if node not in indices:
            visit(node)
    return tuple(sorted(components))
